### ISSUE TITLE
Comparison with ocaml-posix and ExtUnix

### ISSUE THREAD

**Issue by MisterDA** [ocaml-sys/libc.ml#1]
Hi! Thanks for this interesting project!
I'm wondering how it compares to [savonet/ocaml-posix](https://github.com/savonet/ocaml-posix) (ctypes-generated bindings) and [ExtUnix](https://github.com/ygrek/extunix) (hand-written bindings for various libc, POSIX, Unix, and Windows APIs). Could you explain how `libc.ml` differs?

**Comment by leostera** [comment]
Hi @MisterDA! Thanks for asking, `libc.ml` will eventually be fully generated with `ocaml-bindgen` but I just really needed some of these constants in place to build a few things for Riot.

And by fully generated I mean that we will essentially have a big thick .h that includes all of the things we need for a given platform, and use the ocaml-bindgen tool to automatically generate all the OCaml constants, values, externals, etc, _and_ all the C shim code needed to access system libraries.

Hope this helps!

**Comment by MisterDA** [comment]
Thanks for the explanation :)
